### ISSUE TITLE
Add-on does not compile

### ISSUE THREAD

**Issue by BryanHunt** [indexiatech/ember-components#59]
I'm trying to use the addon with ember-cli 0.1.6, ember 1.10 beta 3, and htmlbars.  When I run ember server, I get:

```javascript
Path or pattern "vendor/ember-components/vendor/ic-styled/main.js" did not match any files
Error: Path or pattern "vendor/ember-components/vendor/ic-styled/main.js" did not match any files
    at Object.multiGlob (/Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at $$$internal$$tryCatch (/Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:473:11)
    at Object.$$rsvp$asap$$flush [as _onImmediate] (/Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by asaf** [comment]
Please use the separated addons. See readme file for links.
