### ISSUE TITLE
Ember Server cannot start after install

### ISSUE THREAD

**Issue by joshpfosi** [indexiatech/ember-components#62]
I eliminated this error by using the only component I needed (modals), but I thought I'd report it nonetheless.

The following series of commands resulted in the following error when I tried to start a server:

```
npm install --save-dev ember-cli-components
```

```
|
> ember-components@0.2.0 postinstall /Users/joshpfosi/jobs-tuftsdaily/ember/node_modules/ember-cli-components/node_modules/ember-components
> bower install

bower ember#^1.5.1              cached git://github.com/components/ember.git#1.9.1
bower ember#^1.5.1            validate 1.9.1 against git://github.com/components/ember.git#^1.5.1
bower ic-styled#~1.1.6          cached git://github.com/instructure/ic-styled.git#1.1.7
bower ic-styled#~1.1.6        validate 1.1.7 against git://github.com/instructure/ic-styled.git#~1.1.6
bower ember-qunit#0.1.3         cached git://github.com/rpflorence/ember-qunit.git#0.1.3
bower ember-qunit#0.1.3       validate 0.1.3 against git://github.com/rpflorence/ember-qunit.git#0.1.3
bower ember-utils#~0.1.0        cached git://github.com/indexiatech/ember-utils.git#0.1.0
bower ember-utils#~0.1.0      validate 0.1.0 against git://github.com/indexiatech/ember-utils.git#~0.1.0
bower ember#>=1.2.0 <1.8.0      cached git://github.com/components/ember.git#1.7.1
bower ember#>=1.2.0 <1.8.0    validate 1.7.1 against git://github.com/components/ember.git#>=1.2.0 <1.8.0
bower jquery#>= 1.7.0 < 2.2.0   cached git://github.com/jquery/jquery.git#2.1.3
bower jquery#>= 1.7.0 < 2.2.0 validate 2.1.3 against git://github.com/jquery/jquery.git#>= 1.7.0 < 2.2.0
bower handlebars#>= 1.0.0 < 2.0.0           cached git://github.com/components/handlebars.js.git#1.3.0
bower handlebars#>= 1.0.0 < 2.0.0         validate 1.3.0 against git://github.com/components/handlebars.js.git#>= 1.0.0 < 2.0.0
bower handlebars#>= 2.0.0 < 3.0.0           cached git://github.com/components/handlebars.js.git#2.0.0
bower handlebars#>= 2.0.0 < 3.0.0         validate 2.0.0 against git://github.com/components/handlebars.js.git#>= 2.0.0 < 3.0.0

Unable to find a suitable version for handlebars, please choose one:
    1) handlebars#>= 1.0.0 < 2.0.0 which resolved to 1.3.0 and is required by ember#1.7.1
    2) handlebars#>= 2.0.0 < 3.0.0 which resolved to 2.0.0 and is required by ember#1.9.1Prefix the choice with ! to persist it to bower.json

? Answer:: 1
bower ember-utils#~0.1.0                   install ember-utils#0.1.0
bower ic-styled#~1.1.6                     install ic-styled#1.1.7
bower ember-qunit#0.1.3                    install ember-qunit#0.1.3
bower ember#>=1.2.0 <1.8.0                 install ember#1.7.1
bower handlebars#>= 1.0.0 < 2.0.0          install handlebars#1.3.0
bower jquery#>= 1.7.0 < 2.2.0              install jquery#2.1.3

ember-utils#0.1.0 bower_components/ember-utils

ic-styled#1.1.7 bower_components/ic-styled
└── ember#1.7.1

ember-qunit#0.1.3 bower_components/ember-qunit
└── ember#1.7.1

ember#1.7.1 bower_components/ember
├── handlebars#1.3.0
└── jquery#2.1.3

handlebars#1.3.0 bower_components/handlebars

jquery#2.1.3 bower_components/jquery
ember-cli-components@0.2.0 node_modules/ember-cli-components
└── ember-components@0.2.0
```

```
ember server --proxy http://localhost:3000
```

```
version: 0.1.7
Proxying to http://localhost:3000
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
Path or pattern "vendor/ember-components/vendor/ic-styled/main.js" did not match any files
Error: Path or pattern "vendor/ember-components/vendor/ic-styled/main.js" did not match any files
    at Object.multiGlob (/Users/joshpfosi/jobs-tuftsdaily/ember/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/Users/joshpfosi/jobs-tuftsdaily/ember/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/Users/joshpfosi/jobs-tuftsdaily/ember/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /Users/joshpfosi/jobs-tuftsdaily/ember/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at $$$internal$$tryCatch (/Users/joshpfosi/jobs-tuftsdaily/ember/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/joshpfosi/jobs-tuftsdaily/ember/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/Users/joshpfosi/jobs-tuftsdaily/ember/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:473:11)
    at Object.$$rsvp$asap$$flush [as _onImmediate] (/Users/joshpfosi/jobs-tuftsdaily/ember/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by asaf** [comment]
Hey,

Please use the separated components as listed in the main page!

Thanks

**Comment by magnayn** [comment]
It might make some kind of sense if the website didn't give wrong information

http://indexiatech.github.io/ember-components/#/getstarted :

Install the components addon
npm install --save-dev ember-cli-components

**Comment by bostondevin** [comment]
+1 The directions are whacked - I wasted an hour of my life i'll never get back

**Comment by rileslovesyall** [comment]
I'm having this same issue-- how do I roll back? I went to my last commit before making these changes, and I'm still getting the error!
