### ISSUE TITLE
Broken installation by using ember-cli-components

### ISSUE THREAD

**Issue by zekefast** [indexiatech/ember-components#64]
As far as I understand to get bootstrap stylies I need to install `ember-components` and such parts as `ember-forms` are optional and depends on the project requirements.

When I followed manual [here](http://indexiatech.github.io/ember-components/#/getstarted) and installed ember components as `ember-cli` addon and then run build I got follow errors:

```
$ ember s
version: 0.1.7
Could not find watchman, falling back to NodeWatcher for file system events
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
Path or pattern "vendor/ember-components/vendor/ic-styled/main.js" did not match any files
Error: Path or pattern "vendor/ember-components/vendor/ic-styled/main.js" did not match any files
    at Object.multiGlob (/frontend/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/frontend/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/frontend/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /frontend/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at $$$internal$$tryCatch (/frontend/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/frontend/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/frontend/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:473:11)
    at Object.$$rsvp$asap$$flush [as _onImmediate] (/frontend/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

Package versions used:
- `ember-cli-components: 0.2.0`
- `ember-components: 0.2.0`
- `ember: 1.9.1`
- `handlebars: 2.0.0`
- `ember-cli: 0.1.7`
- `node: 0.10.35`
- `npm: 2.1.8`
- OS: Debian GNU/Linux (jessy)

**Comment by csprocket777** [comment]
Apparently the "proper way" is to install individual components.
https://github.com/indexiatech/ember-components/issues/62

**Comment by zekefast** [comment]
Thanks. There are so many outdated articles in the net, so it is a bit tricky to find out what the latest the most proper way to install things.

**Comment by asaf** [comment]
@zekefast It's specifically mentioned in the README file to use the individual components :)

Thanks.

**Comment by umdstu** [comment]
@zekefast It also specifically mentions to install ember-components:

```
With ember-cli: npm install --save ember-cli-components
```

So perhaps the README should be a little more verbose, or at least not break the app when installing _only_ the ember-components module?

**Comment by zekefast** [comment]
@umdstu I decided do not use `ember-components` at all. Thanks for the help!

**Comment by shantilal-narola** [comment]
@zekefast, What did you end up using? Ive wasted hours today implementing this and then http://indexiatech.github.io/ember-idx-wysiwyg/#/gettingstarted and no luck

I get an error trying the later and logs for same are 

![screen shot 2017-05-31 at 3 23 52 pm](https://cloud.githubusercontent.com/assets/19901535/26626567/3f11b40c-4615-11e7-8740-58d6b867844e.png)

Can you please help me figure it out?  I might just end up creating an git issue for it. I'm naive to ember and any guidance will be appreciated. Thanks

**Comment by umdstu** [comment]
I personally left Ember long ago as well; been doing AngularJS  and never
looked back. Rails + AngularJS has been a good combo as well.

**Comment by zekefast** [comment]
> @zekefast, What did you end up using?

@shantilal-narola, I wrote my own components mostly.
