### ISSUE TITLE
Merge error: file .gitkeep exists

### ISSUE THREAD

**Issue by mkalita** [indexiatech/ember-components#67]
```
$ ember server
version: 0.2.0-beta.1
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
Merge error: file .gitkeep exists in /Users/me/projects/app/node_modules/ember-idx-accordion/vendor and /Users/me/projects/app/tmp/tree_merger-tmp_dest_dir-ouKqxCWm.tmp
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
```

I have read that this would help:

```
rm -rf node_modules
npm cache clear
npm install
```

but it didn't.

**Comment by ldminoc** [comment]
Experiencing the same error when trying to use list and tree. Also using ember 0.2.0-beta.1. Setting the `{ overwrite: true }` option in each of the component's brocfile doesn't appear to have any effect.

```
Merge error: file .gitkeep exists in /Volumes/R10Data/Dev/workspaces/ember/1.11.0-beta4/xtardis/node_modules/ember-idx-list/vendor and /Volumes/R10Data/Dev/workspaces/ember/1.11.0-beta4/xtardis/tmp/tree_merger-tmp_dest_dir-KYB4XEbF.tmp
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
Error: Merge error: file .gitkeep exists in /Volumes/R10Data/Dev/workspaces/ember/1.11.0-beta4/xtardis/node_modules/ember-idx-list/vendor and /Volumes/R10Data/Dev/workspaces/ember/1.11.0-beta4/xtardis/tmp/tree_merger-tmp_dest_dir-KYB4XEbF.tmp
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
at mergeRelativePath (/Volumes/R10Data/Dev/workspaces/ember/1.11.0-beta4/xtardis/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:98:21)
at /Volumes/R10Data/Dev/workspaces/ember/1.11.0-beta4/xtardis/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:23:5
at lib$rsvp$$internal$$tryCatch (/Volumes/R10Data/Dev/workspaces/ember/1.11.0-beta4/xtardis/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
at lib$rsvp$$internal$$invokeCallback (/Volumes/R10Data/Dev/workspaces/ember/1.11.0-beta4/xtardis/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
at lib$rsvp$$internal$$publish (/Volumes/R10Data/Dev/workspaces/ember/1.11.0-beta4/xtardis/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
at lib$rsvp$asap$$flush (/Volumes/R10Data/Dev/workspaces/ember/1.11.0-beta4/xtardis/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
at process._tickCallback (node.js:355:11)
```

**Comment by wayne-o** [comment]
Same here :/
