### ISSUE TITLE
not compatible with latest CLI 0.2.0 + Node 0.12.0 deprecation of the vendor directory in favor of bower_components directory

### ISSUE THREAD

**Issue by robneville73** [indexiatech/ember-components#69]
index.js says:

``` javascript
EmberCLIEmberComponentsAjax.prototype.included = function included(app) {
  this.app = app;
  var options = this.app.options.emberComponentsOptions || {enabled: true};

  if (options.enabled) {
    this.app.import('vendor/ember-components/vendor/ic-styled/main.js');
    this.app.import('vendor/ember-components/vendor/ember-utils/dist/globals/main.js');
    this.app.import('vendor/ember-components/dist/globals/main.js');
  }
};
```

Haven't tested it all yet, but got it to compile and run ember serve OK changing it to:

``` javascript
EmberCLIEmberComponentsAjax.prototype.included = function included(app) {
  this.app = app;
  var options = this.app.options.emberComponentsOptions || {enabled: true};

  if (options.enabled) {
    this.app.import('bower_components/ic-styled/main.js');
    this.app.import('bower_components/ember-utils/dist/globals/main.js'); <--- not sure where this was supposed to point...I think it was a bug maybe in and of itself
    this.app.import('bower_components/ember-components/dist/globals/main.js');
  }
};
```

if you don't do this then you get: Path or pattern "vendor/ember-components/vendor/ic-styled/main.js" did not match any files because of course the /vendor directory is no more.

**Comment by robneville73** [comment]
Adding output from ember serve:

```
Livereload server on port 35729
Serving on http://localhost:4200/
Path or pattern "vendor/ember-components/vendor/ic-styled/main.js" did not match any files
Error: Path or pattern "vendor/ember-components/vendor/ic-styled/main.js" did not match any files
    at Object.multiGlob (/Users/rneville/loft-mobile/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/Users/rneville/loft-mobile/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/Users/rneville/loft-mobile/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /Users/rneville/loft-mobile/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/Users/rneville/loft-mobile/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/rneville/loft-mobile/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/rneville/loft-mobile/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/rneville/loft-mobile/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by robneville73** [comment]
Okay, I see several references saying you have to do each component separately or else you get this problem....gents, your own website does NOT make this clear at all [http://indexiatech.github.io/ember-components/#/getstarted] shows you just doing npm install on the ember-cli-components, [https://github.com/indexiatech/ember-components] in installation section shows the same thing and in fact references the getting started page I linked earlier. Only I click on one of the components and scroll down to it's installation section do you see installing the component individually.

Strongly recommend cleaning up main readme file.
